/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientspmotorbet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Color;
import java.awt.Font; 
import java.awt.Graphics; 
import java.awt.Graphics2D; 
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
//Hanzallah.mahsood@yahoo.com for any question

/**
 *
 * @author paolo
 */
public class clientSPMotorbetGUI extends javax.swing.JFrame {
    private clientSPMotorbet clientSPMotorBet;
    private List<Quotazione> listaQuote ;
    private List<String> listaPiloti;
    private List<String> listaGare ;
    private List<String> listaCampionati ;
    private String selCampionato;
    private String selGara;
    private String selPilota[];
    DefaultTableModel DBmodel;
    DefaultTableModel DBmodel2;
    DefaultTableModel DBmodel3;
    DefaultTableModel DBmodel4;
    Bet b1;
    BetLine bl1, bl_rm;
    String notizie="Da martedì arriveranno aggiornamenti al progetto 2016 incentrati sulla ricerca delle prestazioni-Tante novità concentrate: dall’S - Duct alle forme riviste, fino ai supporti dell’ala, anch’essa leggermente modificata - Le prime reazioni dei piloti riguardo le modifiche regolamentari annunciate dalla FIA. Hamilton: basterebbe fare macchine più leggere - Dopo i 119 giri dell’esordio sulla MP4-31, il pilota spagnolo racconta le prime sensazioni sul nuovo progetto - Ecco finalmente la Ferrari 2016. Si chiama SF16-H e come annunciato ha colore bianco in tutta la parte superiore - Anche la gara 2 dell’appuntamento marocchino del WTCC sul circuito di Marrakech ha offerto nuovamente uno spettacolo condotto essenzialmente dalla Citroën C-Elysée: stavolta, però, sul podio si è accaparrato la prima posizione il pilota Sébastien Loeb con il tempo di 47’50”589.";
    
    /**
     * Creates new form clientSPMotorbet
     */
    public clientSPMotorbetGUI() {
        initComponents();
        initComponent0();
        clientSPMotorBet = clientSPMotorbet.getInstance();      //definisce l'istanza Singleton di clientSPMotorBet    
    }
    //clientSPMotorbet clientSP = new clientSPMotorbet();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponent0() {
        PannGioco.setVisible(false);
        PannTabQuote.setVisible(false);
        PannGiocate.setVisible(false);
        labselcampionato.setVisible(false);
        labselgara.setVisible(false);
        labselpilota.setVisible(false);
        campionato.setVisible(false);
        gara.setVisible(false);
        pilota.setVisible(false);
        aggPuntata.setVisible(false);
        PannBetLines.setVisible(false);
        labQuotaTotale.setVisible(false);
        quotaTotale.setVisible(false);
        rimPuntata.setVisible(false);
        labImporto.setVisible(false);
        importo.setVisible(false);
        labVincitaPotenziale.setVisible(false);
        vincitaPotenziale.setVisible(false);
        calcolaVincitaPotenziale.setVisible(false);
        Conferma.setVisible(false);
        tabBet.setVisible(false);
        info.setText("");
        info.setVisible(false);
        PannDettBettline.setVisible(false);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannGioco = new javax.swing.JPanel();
        labusername = new javax.swing.JLabel();
        labsaldo = new javax.swing.JLabel();
        labbenvenuto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        insScommessa = new javax.swing.JButton();
        visScommessa = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        labselcampionato = new javax.swing.JLabel();
        campionato = new javax.swing.JComboBox<>();
        info = new javax.swing.JLabel();
        labselgara = new javax.swing.JLabel();
        gara = new javax.swing.JComboBox<>();
        labselpilota = new javax.swing.JLabel();
        pilota = new javax.swing.JComboBox<>();
        PannTabQuote = new javax.swing.JScrollPane();
        tabQuote = new javax.swing.JTable();
        aggPuntata = new javax.swing.JButton();
        PannBetLines = new javax.swing.JScrollPane();
        betLines = new javax.swing.JTable();
        labQuotaTotale = new javax.swing.JLabel();
        quotaTotale = new javax.swing.JTextField();
        rimPuntata = new javax.swing.JButton();
        labImporto = new javax.swing.JLabel();
        labVincitaPotenziale = new javax.swing.JLabel();
        importo = new javax.swing.JTextField();
        vincitaPotenziale = new javax.swing.JTextField();
        calcolaVincitaPotenziale = new javax.swing.JButton();
        Conferma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PannGiocate = new javax.swing.JPanel();
        PannDettBettline = new javax.swing.JScrollPane();
        tabBetline = new javax.swing.JTable();
        dettBet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabBet = new javax.swing.JTable();
        indietro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PannLogin = new javax.swing.JPanel();
        userlab = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        benvenuto = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        passlab = new javax.swing.JLabel();
        loginlab = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PannGioco.setBackground(new java.awt.Color(0, 0, 0));
        PannGioco.setMinimumSize(new java.awt.Dimension(1820, 900));
        PannGioco.setPreferredSize(new java.awt.Dimension(1820, 900));
        PannGioco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labusername.setForeground(new java.awt.Color(255, 255, 255));
        labusername.setText("jLabel1");
        PannGioco.add(labusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 140, -1));

        labsaldo.setForeground(new java.awt.Color(255, 255, 255));
        labsaldo.setText("jLabel1");
        PannGioco.add(labsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 30, 130, -1));

        labbenvenuto.setForeground(new java.awt.Color(255, 255, 255));
        labbenvenuto.setText("Benvenuto");
        PannGioco.add(labbenvenuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(204, 0, 0));
        PannGioco.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 170, 1660, 10));

        insScommessa.setText("Scommetti");
        insScommessa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insScommessaActionPerformed(evt);
            }
        });
        PannGioco.add(insScommessa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        visScommessa.setText("Le tue scommesse");
        visScommessa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visScommessaActionPerformed(evt);
            }
        });
        PannGioco.add(visScommessa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 130, -1, -1));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        PannGioco.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 20, -1, -1));

        labselcampionato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labselcampionato.setForeground(new java.awt.Color(255, 255, 255));
        labselcampionato.setText("Seleziona Campionato");
        PannGioco.add(labselcampionato, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        campionato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        campionato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campionatoActionPerformed(evt);
            }
        });
        PannGioco.add(campionato, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        info.setForeground(new java.awt.Color(255, 255, 255));
        PannGioco.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 174, 90, 20));

        labselgara.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labselgara.setForeground(new java.awt.Color(255, 255, 255));
        labselgara.setText("Seleziona Gara");
        PannGioco.add(labselgara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        gara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        gara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garaActionPerformed(evt);
            }
        });
        PannGioco.add(gara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        labselpilota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labselpilota.setForeground(new java.awt.Color(255, 255, 255));
        labselpilota.setText("Seleziona Pilota");
        PannGioco.add(labselpilota, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        pilota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        pilota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotaActionPerformed(evt);
            }
        });
        PannGioco.add(pilota, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        PannTabQuote.setBackground(new java.awt.Color(255, 255, 255));

        tabQuote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cognome", "Posizione", "Quota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PannTabQuote.setViewportView(tabQuote);
        if (tabQuote.getColumnModel().getColumnCount() > 0) {
            tabQuote.getColumnModel().getColumn(0).setHeaderValue("Nome");
            tabQuote.getColumnModel().getColumn(1).setHeaderValue("Cognome");
            tabQuote.getColumnModel().getColumn(2).setHeaderValue("Posizione");
            tabQuote.getColumnModel().getColumn(3).setHeaderValue("Quota");
        }

        PannGioco.add(PannTabQuote, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 388, 108));

        aggPuntata.setText("Seleziona e Aggiungi Puntata");
        aggPuntata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggPuntataActionPerformed(evt);
            }
        });
        PannGioco.add(aggPuntata, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, -1, -1));

        PannBetLines.setBackground(new java.awt.Color(255, 255, 255));

        betLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cognome", "Campionato", "Gara", "Posizione", "Quota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PannBetLines.setViewportView(betLines);

        PannGioco.add(PannBetLines, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 861, 108));

        labQuotaTotale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labQuotaTotale.setForeground(new java.awt.Color(255, 255, 255));
        labQuotaTotale.setText("Quota Totale");
        PannGioco.add(labQuotaTotale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 540, -1, 20));
        PannGioco.add(quotaTotale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 540, 86, -1));

        rimPuntata.setText("Rimuovi Puntata");
        rimPuntata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rimPuntataActionPerformed(evt);
            }
        });
        PannGioco.add(rimPuntata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 510, 170, -1));

        labImporto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labImporto.setForeground(new java.awt.Color(255, 255, 255));
        labImporto.setText("Importo €");
        PannGioco.add(labImporto, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 570, 80, 20));

        labVincitaPotenziale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labVincitaPotenziale.setForeground(new java.awt.Color(255, 255, 255));
        labVincitaPotenziale.setText("Vincita Potenziale €");
        PannGioco.add(labVincitaPotenziale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 570, 140, 20));

        importo.setMinimumSize(new java.awt.Dimension(6, 23));
        importo.setPreferredSize(new java.awt.Dimension(6, 23));
        importo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importoActionPerformed(evt);
            }
        });
        PannGioco.add(importo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 90, 23));
        PannGioco.add(vincitaPotenziale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 570, 86, -1));

        calcolaVincitaPotenziale.setText("Calcola Vincita Potenziale");
        calcolaVincitaPotenziale.setMaximumSize(new java.awt.Dimension(153, 20));
        calcolaVincitaPotenziale.setMinimumSize(new java.awt.Dimension(153, 20));
        calcolaVincitaPotenziale.setPreferredSize(new java.awt.Dimension(153, 20));
        calcolaVincitaPotenziale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcolaVincitaPotenzialeActionPerformed(evt);
            }
        });
        PannGioco.add(calcolaVincitaPotenziale, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 180, 23));

        Conferma.setText("Conferma");
        Conferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfermaActionPerformed(evt);
            }
        });
        PannGioco.add(Conferma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 600, 178, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientspmotorbet/S&p.png"))); // NOI18N
        PannGioco.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 430, 110));

        jPanel2.setBackground(new java.awt.Color(254, 91, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        PannGioco.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1820, 50));

        jPanel1.setPreferredSize(new java.awt.Dimension(1820, 800));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientspmotorbet/WRC3_hero.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(1820, 800));
        jLabel4.setMinimumSize(new java.awt.Dimension(1820, 800));
        jLabel4.setPreferredSize(new java.awt.Dimension(1820, 800));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1830, 690);

        PannGioco.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1820, 810));

        PannGiocate.setBackground(new java.awt.Color(0, 0, 0));
        PannGiocate.setMinimumSize(new java.awt.Dimension(1820, 900));
        PannGiocate.setPreferredSize(new java.awt.Dimension(1820, 900));
        PannGiocate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabBetline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Pilota", "Cognome Pilota", "Campionato", "Gara", "Posizione", "Quota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PannDettBettline.setViewportView(tabBetline);

        PannGiocate.add(PannDettBettline, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 840, 280));

        dettBet.setText("Visualizza Bet Selezionata");
        dettBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dettBetActionPerformed(evt);
            }
        });
        PannGiocate.add(dettBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 220, -1));

        tabBet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Importo", "Vincita Potenziale", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabBet);

        PannGiocate.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 280));

        indietro.setText("Indietro");
        indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroActionPerformed(evt);
            }
        });
        PannGiocate.add(indietro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 70, -1, -1));
        PannGiocate.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 400, 100));

        PannLogin.setPreferredSize(new java.awt.Dimension(1820, 852));
        PannLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlab.setForeground(new java.awt.Color(255, 255, 255));
        userlab.setText("Username");
        PannLogin.add(userlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 285, 100, -1));

        password.setToolTipText("");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        PannLogin.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 330, 120, 30));

        benvenuto.setFont(new java.awt.Font("Cantarell", 2, 36)); // NOI18N
        benvenuto.setForeground(new java.awt.Color(255, 255, 255));
        benvenuto.setText("BENVENUTO SU S&P MOTORBET");
        PannLogin.add(benvenuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 620, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        PannLogin.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 383, 85, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        PannLogin.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 282, 120, 30));

        passlab.setForeground(new java.awt.Color(255, 255, 255));
        passlab.setText("Password");
        PannLogin.add(passlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 333, 100, -1));

        loginlab.setForeground(new java.awt.Color(255, 255, 255));
        loginlab.setText("LOGIN");
        PannLogin.add(loginlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 250, 70, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        PannLogin.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 383, 85, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientspmotorbet/spmotorbet.png"))); // NOI18N
        PannLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannGioco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PannGiocate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PannLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannGioco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PannGiocate, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PannLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    int x = 2000, y = 220;
    @Override
    public void paint(Graphics g){
        Graphics2D g2 = (Graphics2D)g;  
        Font font = new Font("Tahoma",Font.BOLD+Font.PLAIN,11); 
        super.paint(g);  
        g2.setFont(font);      
        g2.setColor(Color.white);  
        g2.drawString(info.getText(),x,y);

        try{
            Thread.sleep(100);}
        catch(Exception ex){}    
            x-=10;         
        if(x==-5000){
            x=2000;
        }       
        repaint();
    }
 
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        if(!(username.getText().equals("")||password.getText().equals(""))){
            if(clientSPMotorBet.login(username.getText(), password.getText())){
                //Login effettuata, si passa all'interfaccia di gioco del cliente
                PannLogin.setVisible(false);    //l'area login scompare
                PannGioco.setVisible(true);     //appare l'area di gioco
                info.setText(notizie);
                labusername.setText(clientSPMotorBet.getClienteCorrente().getNome()+" "+clientSPMotorBet.getClienteCorrente().getCognome());
                labsaldo.setText("Saldo € " + clientSPMotorBet.getClienteCorrente().getContoPersonale().getSaldo());
            }else{
                JOptionPane.showMessageDialog(null, "Connessione Fallita: username o password errati!");
                username.setText("");
                password.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Inserire dei valori nei campi Username e Password");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        username.setText("");
        password.setText("");
        username.revalidate();
        password.revalidate();
    }//GEN-LAST:event_resetActionPerformed

    private void calcolaVincitaPotenzialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcolaVincitaPotenzialeActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.00");
        df.setGroupingSize(3);
        try{
            if(!importo.getText().equals("")){
                if(Float.parseFloat(quotaTotale.getText())>0) {
                    if(clientSPMotorBet.VerificaImporto(Float.parseFloat(importo.getText()))){
                        String impformatted = df.format(Float.parseFloat(importo.getText()));
                        impformatted = impformatted.replace(",", ".");
                        float imp = Float.parseFloat(impformatted);
                        float qt = Float.parseFloat(quotaTotale.getText());
                        float vp = imp * qt;
                        String impformatted2 = df.format(vp);
                        impformatted2 = impformatted2.replace(",", ".");
                        vincitaPotenziale.setText(impformatted2);
                    }else{
                        JOptionPane.showMessageDialog(null, "Saldo insufficiente!!");
                        importo.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nessuna Puntata presente!");
                    importo.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Nessuna importo inserito!"); 
                importo.setText("");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Errore: importo non valido", "Error", JOptionPane.ERROR_MESSAGE);
            importo.setText("");
            vincitaPotenziale.setText("");
        }
    }//GEN-LAST:event_calcolaVincitaPotenzialeActionPerformed

    private void importoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importoActionPerformed

    private void rimPuntataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rimPuntataActionPerformed
        // TODO add your handling code here:  
        clientSPMotorBet.getBet().delPuntata((betLines.getSelectedRow()));
        DBmodel2.removeRow(betLines.getSelectedRow());
        quotaTotale.setText(Float.toString(clientSPMotorBet.getBet().aggQuotaTotale()));
        vincitaPotenziale.setText("");
        importo.setText("");
    }//GEN-LAST:event_rimPuntataActionPerformed

    private void aggPuntataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggPuntataActionPerformed
        // TODO add your handling code here:
        DBmodel2 = (DefaultTableModel)betLines.getModel();
       
        boolean res = clientSPMotorBet.aggPuntata(DBmodel.getValueAt(tabQuote.getSelectedRow(), 0).toString(), DBmodel.getValueAt(tabQuote.getSelectedRow(), 1).toString(), selCampionato, selGara, (int)DBmodel.getValueAt(tabQuote.getSelectedRow(), 2), (float)DBmodel.getValueAt(tabQuote.getSelectedRow(), 3));
        if(res){
            DBmodel2.addRow(new Object[]{DBmodel.getValueAt(tabQuote.getSelectedRow(), 0).toString(), DBmodel.getValueAt(tabQuote.getSelectedRow(), 1).toString(), selCampionato, selGara, DBmodel.getValueAt(tabQuote.getSelectedRow(), 2).toString(), DBmodel.getValueAt(tabQuote.getSelectedRow(), 3).toString()});
            quotaTotale.setText(Float.toString(clientSPMotorBet.getBet().aggQuotaTotale()));
        }else{
            JOptionPane.showMessageDialog(null, "Puntata già presente");
        }
    }//GEN-LAST:event_aggPuntataActionPerformed

    private void pilotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotaActionPerformed
        // TODO add your handling code here:
        PannBetLines.setVisible(true);
        PannTabQuote.setVisible(true);
        aggPuntata.setVisible(true);
        labQuotaTotale.setVisible(true);
        quotaTotale.setVisible(true);
        rimPuntata.setVisible(true);
        labImporto.setVisible(true);
        importo.setVisible(true);
        labVincitaPotenziale.setVisible(true);
        vincitaPotenziale.setVisible(true);
        calcolaVincitaPotenziale.setVisible(true);
        Conferma.setVisible(true);
        DBmodel = (DefaultTableModel)tabQuote.getModel();
        while(DBmodel.getRowCount()!=0){
            DBmodel.removeRow(0);
        }
        
        try{
        listaQuote = new ArrayList<Quotazione>();
        selPilota = pilota.getSelectedItem().toString().split(" ");
        System.out.println(selPilota[0] + " " + selPilota[1]);
        
        listaQuote = this.clientSPMotorBet.popolaQuote(selCampionato, selGara, selPilota);
        for(int i = 0; i<(listaQuote.size()); i++){
            DBmodel = (DefaultTableModel)tabQuote.getModel();
            DBmodel.addRow(new Object[]{listaQuote.get(i).getNomePilota(), listaQuote.get(i).getCognomePilota(), listaQuote.get(i).getPosizione(), listaQuote.get(i).getQuota()});
        }
        }catch(Exception e){}
            
       
    }//GEN-LAST:event_pilotaActionPerformed

    private void garaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garaActionPerformed
        
    // TODO add your handling code here:
        PannTabQuote.setVisible(true);
        aggPuntata.setVisible(true);
        labQuotaTotale.setVisible(true);
        quotaTotale.setVisible(true);
        
        pilota.removeAllItems();
        pilota.addItem("---");
        labselpilota.setVisible(true);
        pilota.setVisible(true);
        
        try{
        selGara = gara.getSelectedItem().toString();
        System.out.println(selGara);
        listaPiloti = new ArrayList<String>();
        listaPiloti = this.clientSPMotorBet.popolaPilota(selCampionato, selGara);
        for(int i = 0; i<(listaPiloti.size()); i++){
            pilota.addItem(listaPiloti.get(i));
        }
        }catch(Exception e){}
       
    }//GEN-LAST:event_garaActionPerformed

    private void campionatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campionatoActionPerformed
       
         // TODO add your handling code here:
        if(campionato.getSelectedItem().toString().equals("---")){
            labselgara.setVisible(false);
            gara.setVisible(false);
            gara.removeAllItems();
            gara.addItem("---");
            labselpilota.setVisible(false);
            pilota.setVisible(false);
        }
        else{
            gara.removeAllItems();
            labselgara.setVisible(true);
            gara.setVisible(true);
            gara.addItem("---");
        }
        try{
        selCampionato = campionato.getSelectedItem().toString();
        System.out.println(selCampionato);
        listaGare = new ArrayList<String>();
        listaGare = this.clientSPMotorBet.popolaGara(selCampionato);
        for(int i = 0; i<(listaGare.size()); i++){
            gara.addItem(listaGare.get(i));
        }
        }catch(Exception e){}
      
       
    }//GEN-LAST:event_campionatoActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        PannGiocate.setVisible(false);
        PannGioco.setVisible(false);
        PannLogin.setVisible(true);
        labusername.setText("");
        labsaldo.setText("");
        labselcampionato.setVisible(false);
        labselgara.setVisible(false);
        labselpilota.setVisible(false);
        campionato.setSelectedItem("---");
        campionato.setVisible(false);
        gara.setVisible(false);
        pilota.setVisible(false);
        username.setText("");
        password.setText("");
        username.revalidate();
        password.revalidate();
        insScommessa.setEnabled(true);
        tabBet.setVisible(false);
        info.setText("");
        PannTabQuote.setVisible(false);
        DBmodel = (DefaultTableModel)tabQuote.getModel();
        while(DBmodel.getRowCount()!=0){
            DBmodel.removeRow(0);
        }
        aggPuntata.setVisible(false);
        PannBetLines.setVisible(false);
        DBmodel = (DefaultTableModel)betLines.getModel();
        while(DBmodel.getRowCount()!=0){
            DBmodel.removeRow(0);
        }
        labQuotaTotale.setVisible(false);
        quotaTotale.setVisible(false);
        quotaTotale.setText("");
        rimPuntata.setVisible(false);
        labImporto.setVisible(false);
        importo.setVisible(false);
        importo.setText("");
        labVincitaPotenziale.setVisible(false);
        vincitaPotenziale.setVisible(false);
        vincitaPotenziale.setText("");
        calcolaVincitaPotenziale.setVisible(false);
        Conferma.setVisible(false);
        PannDettBettline.setVisible(false);
        clientSPMotorBet.logout();
    }//GEN-LAST:event_logoutActionPerformed

    private void insScommessaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insScommessaActionPerformed
        // TODO add your handling code here:
         listaCampionati = new ArrayList<String>();
        labselcampionato.setVisible(true);
        campionato.setVisible(true);
        clientSPMotorBet.istanzaBet();
        listaCampionati = clientSPMotorBet.popolaCampionato();
      
          for(int i=0;i<listaCampionati.size();i++){
                 
             campionato.addItem( listaCampionati.get(i));
             }
        
    }//GEN-LAST:event_insScommessaActionPerformed

    private void ConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfermaActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.00");
        df.setGroupingSize(3);
        if(!vincitaPotenziale.getText().equals("")){
            String impformatted = df.format(Float.parseFloat(importo.getText()));
            impformatted = impformatted.replace(",", ".");
            clientSPMotorBet.getBet().setImporto(Float.parseFloat(impformatted));
            clientSPMotorBet.getBet().setVincitaPotenziale(Float.parseFloat(vincitaPotenziale.getText()));
            //Inserimento di Bet e relative BetLine al'interno del DB
           try{
                if(clientSPMotorBet.confermaGiocata()){
                    DBmodel2 = (DefaultTableModel)betLines.getModel();
                    while(DBmodel2.getRowCount()!=0){
                        DBmodel2.removeRow(0);
                    } 
                    JOptionPane.showMessageDialog(null, "Scommessa registrata con successo!");
                    labsaldo.setText("€ "+Float.toString(clientSPMotorBet.getClienteCorrente().getContoPersonale().getSaldo()));
                    importo.setText("");
                    quotaTotale.setText(Float.toString(clientSPMotorBet.getBet().aggQuotaTotale()));
                    vincitaPotenziale.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Errore: inserimento scommessa fallito", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
            }
            }else{
                JOptionPane.showMessageDialog(null, "Impossibile proseguire: si prega di completare la giocata!"); 
            }
    }//GEN-LAST:event_ConfermaActionPerformed

    private void visScommessaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visScommessaActionPerformed
        
        info.setText("");
       
        DBmodel3 = (DefaultTableModel)tabBet.getModel();
        dettBet.setVisible(true);
        PannGiocate.setVisible(true);
        PannGioco.setVisible(false);
        indietro.setEnabled(true);
        //VISUALIZZIAMO LA BET EFFETTUATA DALL'UTENTE
        tabBet.setVisible(true);
        tabBetline.setVisible(true);
        
        List<Bet> ListaBet = this.clientSPMotorBet.visScommesse();
            for(int i=0;i<ListaBet.size();i++){
                DBmodel3.addRow(new Object[]{ListaBet.get(i).getData(), "€"+" "+ListaBet.get(i).getImporto(), "€"+" "+ListaBet.get(i).getVincitaPotenziale(),ListaBet.get(i).getId()});
            }
            
   
    }//GEN-LAST:event_visScommessaActionPerformed

    
    
    
    
    private void indietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroActionPerformed
        PannDettBettline.setVisible(false);       
        info.setText(notizie);
        PannGiocate.setVisible(false);
        PannDettBettline.setVisible(false);
        tabBet.setVisible(false);
        tabBetline.setVisible(false);
        dettBet.setVisible(false);
        PannGioco.setVisible(true);
        while(DBmodel3.getRowCount()!=0){
            DBmodel3.removeRow(0);
        }
        if(DBmodel4 != null)
        while(DBmodel4.getRowCount()!=0){
            DBmodel4.removeRow(0);
        }
    }//GEN-LAST:event_indietroActionPerformed

    private void dettBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dettBetActionPerformed
        PannDettBettline.setVisible(true);   
        DBmodel4 = (DefaultTableModel)tabBetline.getModel();
        while(DBmodel4.getRowCount()!=0){
            DBmodel4.removeRow(0);
        }
        
       
            List<BetLine> ListaBetLine = clientSPMotorBet.visDetScommessa(DBmodel3.getValueAt(tabBet.getSelectedRow(), 3).toString());
           for(int i=0;i<ListaBetLine.size();i++){
            DBmodel4.addRow(new Object[]{ListaBetLine.get(i).getNomepilota(),ListaBetLine.get(i).getCognomepilota(),ListaBetLine.get(i).getCampionato(),ListaBetLine.get(i).getGara(),ListaBetLine.get(i).getPosizione(),ListaBetLine.get(i).getQuota()});
           }
       
    }//GEN-LAST:event_dettBetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientSPMotorbetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientSPMotorbetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientSPMotorbetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientSPMotorbetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientSPMotorbetGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Conferma;
    private javax.swing.JScrollPane PannBetLines;
    private javax.swing.JScrollPane PannDettBettline;
    private javax.swing.JPanel PannGiocate;
    private javax.swing.JPanel PannGioco;
    private javax.swing.JPanel PannLogin;
    private javax.swing.JScrollPane PannTabQuote;
    private javax.swing.JButton aggPuntata;
    private javax.swing.JLabel benvenuto;
    private javax.swing.JTable betLines;
    private javax.swing.JButton calcolaVincitaPotenziale;
    private javax.swing.JComboBox<String> campionato;
    private javax.swing.JButton dettBet;
    private javax.swing.JComboBox<String> gara;
    private javax.swing.JTextField importo;
    private javax.swing.JButton indietro;
    private javax.swing.JLabel info;
    private javax.swing.JButton insScommessa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labImporto;
    private javax.swing.JLabel labQuotaTotale;
    private javax.swing.JLabel labVincitaPotenziale;
    private javax.swing.JLabel labbenvenuto;
    private javax.swing.JLabel labsaldo;
    private javax.swing.JLabel labselcampionato;
    private javax.swing.JLabel labselgara;
    private javax.swing.JLabel labselpilota;
    private javax.swing.JLabel labusername;
    private javax.swing.JButton login;
    private javax.swing.JLabel loginlab;
    private javax.swing.JButton logout;
    private javax.swing.JLabel passlab;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> pilota;
    private javax.swing.JTextField quotaTotale;
    private javax.swing.JButton reset;
    private javax.swing.JButton rimPuntata;
    private javax.swing.JTable tabBet;
    private javax.swing.JTable tabBetline;
    private javax.swing.JTable tabQuote;
    private javax.swing.JLabel userlab;
    private javax.swing.JTextField username;
    private javax.swing.JTextField vincitaPotenziale;
    private javax.swing.JButton visScommessa;
    // End of variables declaration//GEN-END:variables
}
